#!/bin/sh
#PBS -q rt_HG
#PBS -l select=1
#PBS -l walltime=150:00:00
#PBS -P gag51492

cd $HOME/FOMO

. jobs-abci/environment.sh

mkdir -p job_logs/imagenet-100

python -m experiment model=resnet50 ssl=simclr dataset=imagenet100_balanced num_cycles=8 total_epochs=800 ood_augmentation=true experiment_name=sota_imagenet-100_newmethod train_batch_size=512 use_deepspeed=false log_class_dist=true log_generated_samples=true log_tsne=true num_runs=3 >& job_logs/imagenet-100/newmethod.out
