#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=ResNet50AblationsSupervised
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=48:00:00
#SBATCH --output=job_logs/ResNet50Ablation-%A.out

cd $HOME/FOMO

. jobs/ablations/supervised/ResNet50/OODAugmentationBalanced.sh
. jobs/ablations/supervised/ResNet50/stepwiseBaseline.sh
. jobs/ablations/supervised/ResNet50/UniformGeneration.sh
