. jobs/environment.sh

python -m experiment \
	--model-name ResNet50 \
  --num-runs 3 \
  --imagenet-variant 1k \
	--imbalance-method power_law_imbalance \
	--max-cycles 5 \
	--ood-augmentation \
        --n-epochs-per-cycle 20 \
        --pct-ood 0.15 \
  --batch-size 1024 \
        --use-temperature-schedule \
        --temperature-min 0.1 \
        --temperature-max 1.0 \
        --t-max 400 \
  --experiment_name "Baseline_ResNet50_SimCLR_NewMethod_ImageNet1k"
