#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=ViTSmallAblations-Supervised
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=48:00:00
#SBATCH --output=job_logs/ViTSmallAblations-Supervised-%A.out

cd $HOME/FOMO

. jobs/ablations/supervised/ViTSmall/OODAugmentationBalanced.sh
. jobs/ablations/supervised/ViTSmall/stepwiseBaseline.sh
. jobs/ablations/supervised/ViTSmall/UniformGeneration.sh
