wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.40.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716555837
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 83
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 83
      3:
      - 1
      - 7
      - 13
      - 23
      - 66
      4: 3.10.14
      5: 0.17.0
      6: 4.40.2
      8:
      - 5
      13: darwin-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
